CREATE TABLE IF NOT EXISTS Lama_Bands(
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  music_genre VARCHAR(255) NOT NULL,
  responsible VARCHAR(255) UNIQUE NOT NULL 
);

CREATE TABLE IF NOT EXISTS Lama_Shows(
  id VARCHAR(255) PRIMARY KEY,
  week_day ENUM("FRIDAY", "SATURDAY", "SUNDAY") NOT NULL,
  start_time INT NOT NULL,
  end_time INT NOT NULL,
  band_id VARCHAR(255) NOT NULL,
  FOREIGN KEY(band_id) REFERENCES Lama_Bands(id)
);

CREATE TABLE IF NOT EXISTS Lama_Users(
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM("NORMAL", "ADMIN") NOT NULL DEFAULT "NORMAL"
);
