### user endpoints
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Bruno",
    "email": "bruno@email.com",
    "password": "123456",
    "role": "admin"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "joao@email.com",
    "password": "123456"
}

### band endpoints
GET http://localhost:3003/band/356a1a10-270e-49df-b317-acf9f4cc8102
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0MGMzMGIyLWUzMjUtNGUzZC1iMWIwLTdjZDQxZmYwNmFiNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzMDA4OTEyNiwiZXhwIjoxNjMwMDkyNzI2fQ.l-uSNVVrXBBIgqhxqFYT7D7MPUOVemeROy1KZjobhtU

###
POST http://localhost:3003/band/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0MGMzMGIyLWUzMjUtNGUzZC1iMWIwLTdjZDQxZmYwNmFiNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzMDA4MjE5NywiZXhwIjoxNjMwMDg1Nzk3fQ.LMlQGDuWv7GKBqOdPe-EzQJ4d_MX4v3Ni4G6umkraqY

{
    "name": "Sepultura",
    "musicGenre": "Rock",
    "responsible": "Maria"
}

### show endpoints
GET http://localhost:3003/show/friday
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0MGMzMGIyLWUzMjUtNGUzZC1iMWIwLTdjZDQxZmYwNmFiNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzMDEwMTg3NCwiZXhwIjoxNjMwMTA1NDc0fQ.deTYcvwCOy4aD3bJGgfye9ynf95qihozBsdUeVSKzM8

###
POST http://localhost:3003/show/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0MGMzMGIyLWUzMjUtNGUzZC1iMWIwLTdjZDQxZmYwNmFiNCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYzMDA5NzM5OCwiZXhwIjoxNjMwMTAwOTk4fQ.UNwMCSDQQklmJwSND_9kNy9fywYhnOCIm55UvJrXtF0

{
    "weekDay": "friday",
    "startTime": 11,
    "endTime": 12,
    "bandId": "356a1a10-270e-49df-b317-acf9f4cc8102"
}

